##
# Generic tfscaffold Module Variables
##

variable "aws" {
  type = object({
    account_id   = string
    default_tags = optional(map(string), {})
    partition    = optional(string, "aws")
    region       = string
    url_suffix   = optional(string, "amazonaws.com")
  })
}

variable "module_parents" {
  type        = list(string)
  description = "List of parent module names"
  default     = []
}

variable "unique_ids" {
  type = object({
    # All marked as optional for consistency of code.
    # Whether each is optional depends on the module implementation.
    local   = optional(string, null)
    account = optional(string, null)
    global  = optional(string, null)
  })
}

##
# Variables specific to this Module
##

variable "function_name" {
  type        = string
  description = "Base name of this lambda"
  default     = null
}

variable "function_description" {
  type        = string
  description = "Description of the Lambda"
  default     = null
}

variable "function_module_name" {
  type        = string
  description = "The optional name of the function module as used by the lambda handler, e.g. index or exports. Concatenated with handler_function_name to make, `<var.function_module_name>.<var.handler_function_name>`"
  default     = null
}

variable "handler_function_name" {
  type        = string
  description = "The name of the lambda handler function (passed directly to the Lambda's handler option)"
  default     = "handler"
}

variable "memory" {
  type        = number
  description = "The amount of memory to apply to the created Lambda"
}

variable "timeout" {
  type        = number
  description = "Timeout in seconds of the lambda function invocation"
}

variable "log_retention_in_days" {
  type        = string
  description = "The retention period for the CloudwatchLogs events generated by the lambda function"
}

variable "runtime" {
  type        = string
  description = "The runtime to use for the lambda function"
  default     = null
}

variable "cloudwatch_event_target_input" {
  type        = string
  description = "Optional JSON string to use as constant input for the Cloudwatch Event Target that invokes the lambda if using scheduled events"
  default     = null
}

variable "allowed_triggers" {
  description = "Map of allowed triggers to create Lambda permissions"
  type        = map(any)
  default     = {}
}

variable "schedule" {
  type        = string
  description = "The fully qualified Cloudwatch Events schedule for when to run the lambda function, e.g. rate(1 day) or a cron() expression. Default disables all events resources"
  default     = ""
}

variable "iam_policy_documents" {
  type        = list(string)
  description = "An IAM Policy Document to grant the lambda function access to the API calls it needs. Should be the 'json' attribute of an aws_iam_policy_document data source"
  default     = []
}

variable "lambda_env_vars" {
  type        = map(string)
  description = "Lambda environment parameters map"
  default     = {}
}

variable "architectures" {
  type        = list(string)
  description = "List of architectures to build the lambda for"

  default = [
    "x86_64",
  ]
}

##
# Function Source is either a string containing function code,
# or a directory containing the function source files

variable "function_source_type" {
  type        = string
  description = "The type of function source, either s3, file, directory, image or archive"
}

## EITHER

# A directory we will zip up to create the function archive

variable "function_dir" {
  type        = string
  description = "Relative Lambda function directory path"
  default     = null
}

## OR

# Content that we will write to a file and then zip up to create the function archive

variable "function_source" {
  type        = string
  description = "The source code of the lambda function as a single file expressed as a string"
  default     = null
}

variable "function_file_extension" {
  type        = string
  description = "The function source file extension, e.g. js or py"
  default     = null
}

## OR

# An S3 object in the same region as this function that we will give to the lambda
# principal to use (where it will steal our credentials to access the object)

variable "function_source_s3_key" {
  type        = string
  description = "Key name of the lambda function source Zip archive, stored in an S3 bucket"
  default     = null
}

variable "function_source_s3_bucket" {
  type        = string
  description = "Bucket ID containing the lambda function source Zip archive"
  default     = null
}

variable "function_source_version_id" {
  type        = string
  description = "An optional S3 Object ID for the function source archive"
  default     = null
}

## OR

# The path to a file on disk that contains the lambda function code.
# Primarily used when the archive is in a destination we cannot access,
# but from where the calling module can make the zip content available to us

variable "function_source_archive_file_path" {
  type        = string
  description = "Path to a deployable lambda function archive zip-file on disk"
  default     = null
}

## OR

# The URI for a Container Image that contains the lambda function code.

variable "function_image_uri" {
  type        = string
  description = "The URI for a Container Image that contains the lambda function code"
  default     = null
}

variable "function_image_config" {
  type = object({
    command           = optional(string, null)
    entry_point       = optional(string, null)
    working_directory = optional(string, null)
  })

  description = "The configuration for the Container Image that contains the lambda function code"
  default     = null
}

##

# https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#tracing_config
# PassThrough is default to reduce costs - please see docs for more details
variable "xray_mode" {
  type        = string
  description = "Mode for AWS X-Ray"
  default     = "PassThrough"
}

variable "function_errors" {
  type = object({
    alarm = optional(object({
      name                      = optional(string, null)
      description               = optional(string, null)
      evaluation_periods        = optional(number, 1)
      period                    = optional(number, 120)
      statistic                 = optional(string, "Maximum")
      threshold                 = optional(number, 0)
      actions                   = optional(list(string), [])
      ok_actions                = optional(list(string), [])
      insufficient_data_actions = optional(list(string), [])
      managed_sns_topic         = optional(bool, false)
    }), null)

    async_on_failure_destination = optional(object({
      enabled           = bool
      managed_sns_topic = optional(bool, false)
      topic_arn         = optional(string, null)
    }), {
      enabled = false
    })
  })

  description = <<-EOT
    Function Errors Monitoring Config

    alarm: Config for sync invocations alarm
      * name: The name of the alarm (defaults to the "$${local.unique_id}-errors")
      * description: The description of the alarm (defaults to "Errors > 0 for Lambda $${local.unique_id}")
      * evaluation_periods: The number of periods over which data is compared to the threshold
      * period: The period in seconds over which the specified statistic is applied
      * statistic: The statistic to apply to the alarm's data
      * threshold: The value against which the specified statistic is compared
      * actions: The list of actions to take when the alarm transitions into an ALARM state
      * ok_actions: The list of actions to take when the alarm transitions into an OK state
      * insufficient_data_actions: The list of actions to take when the alarm transitions into an INSUFFICIENT_DATA state
      * managed_sns_topic: Whether to create an SNS topic for the alarm (in addition to the actions specified)

    async_invocations: Config for async invocations alarm
      * enabled: Whether to enable the async invocations alarm
      * managed_sns_topic: Whether to create an SNS topic and an event invoke config for error handling
                           (takes precedence over the topic_arn)
      * topic_arn: If specified, the ARN of the SNS topic to use for the async invocations alarm
  EOT

  default = null
}

variable "sns_logs" {
  type = object({
    iam_role_arn        = string
    success_sample_rate = optional(number)
  })

  description = "The ARN of the IAM Role and Sample Rate to use for delivery feedback logging when creating an AWS SNS Topic"

  default = {
    iam_role_arn = null
  }
}

variable "subscription_arns" {
  type        = list(map(string))
  description = "List of subscriptions for the SNS topic"
  default     = []
}

variable "dead_letter_target_arn" {
  type        = string
  description = "The ARN of the SQS queue or SNS topic to use as the dead-letter target for the lambda function"
  default     = null
}

# NOTE: There is a limit of 5 layers. If you enable the lambda insights that limit
#       goes down to 4 since lamba insights adds a layer.
variable "layers" {
  type        = list(string)
  description = "Additional lambda layers to include. Ignored when edge is true"
  default     = []
}

variable "insights" {
  type = object({
    enabled = optional(bool, false)
    fetch   = optional(bool, true)
    version = optional(string, null)
  })

  description = "Lambda insights layer configuration. Ignored when edge is true"

  default = {
    enabled = false
  }
}

variable "reserved_concurrent_executions" {
  type        = number
  description = "Number of executions to limit Lambda to"
  default     = -1
}

variable "edge" {
  type        = bool
  description = "Whether this lambda is an edge lambda"
  default     = false
}

variable "create_kms_policies" {
  type        = bool
  description = "Whether to create Admin and User IAM policies for the KMS key. Defaults to false"
  default     = false
}

variable "vpc_config" {
  type = object({
    security_group_ids = list(string)
    subnet_ids         = list(string)
  })

  default = null
}
